services:
  client-service:
    build:
      context: ./client
      args:
        VITE_BASE_API_URL: http://localhost:5173/api
    env_file: ./client/.env
    ports:
      - "5173:8081"
    volumes:
      - "./client/nginx.conf:/etc/nginx/nginx.conf"
  placeholder-service:
    build: "./server"
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
